# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=release_shared64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = .
TARGET = $(TARGETDIR)/dome
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lm
LDDEPS +=
LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
VERSION=`git describe --tags`
HASH=`git rev-parse --short HEAD`
SDLCONFIG=$(shell which sdl2-config 1>/dev/null && echo \"sdl2-config\" || echo \""..libdir.."sdl2-config\")
  

define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
	@echo Running postbuild commands
	install_name_tool -change /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib \@executable_path/libSDL2-2.0.0.dylib ./dome
	install_name_tool -change /usr/local/lib/libSDL2-2.0.0.dylib \@executable_path/libSDL2-2.0.0.dylib ./dome
	install_name_tool -add_rpath \@executable_path/libSDL2.0.0.dylib ./dome
endef

ifeq ($(config),release_static64)
OBJDIR = obj/static64/Release/dome
DEFINES += -DDOME_VERSION=\"$(VERSION)\" -DHASH=\"$(HASH)\"
INCLUDES += -isystem src/include -isystem src/include/SDL2
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_LDFLAGS += $(LDFLAGS) -L/Users/aviv.beeri/hobby/dome/src/lib -m64 -lwren  `$(SDLCONFIG) --static-libs` 

else ifeq ($(config),release_shared64)
OBJDIR = obj/shared64/Release/dome
DEFINES += -DDOME_VERSION=\"$(VERSION)\" -DHASH=\"$(HASH)\"
INCLUDES += -isystem src/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_LDFLAGS += $(LDFLAGS) -m64 -lwren `$(SDLCONFIG) --libs` -Lsrc/lib/

else ifeq ($(config),release_static32)
OBJDIR = obj/static32/Release/dome
DEFINES += -DDOME_VERSION=\"$(VERSION)\" -DHASH=\"$(HASH)\"
INCLUDES += -isystem src/include -isystem src/include/SDL2
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_LDFLAGS += $(LDFLAGS) -L/Users/aviv.beeri/hobby/dome/src/lib -m32 -lwren  `$(SDLCONFIG) --static-libs` 

else ifeq ($(config),release_shared32)
OBJDIR = obj/shared32/Release/dome
DEFINES += -DDOME_VERSION=\"$(VERSION)\" -DHASH=\"$(HASH)\"
INCLUDES += -isystem src/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_LDFLAGS += $(LDFLAGS) -m32 -lwren `$(SDLCONFIG) --libs` -Lsrc/lib/

else ifeq ($(config),debug_static64)
OBJDIR = obj/static64/Debug/dome
DEFINES += -DDOME_VERSION=\"$(VERSION)\" -DHASH=\"$(HASH)\" -DDEBUG=1
INCLUDES += -isystem src/include -isystem src/include/SDL2
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_LDFLAGS += $(LDFLAGS) -L/Users/aviv.beeri/hobby/dome/src/lib -m64 -lwren  `$(SDLCONFIG) --static-libs` 

else ifeq ($(config),debug_shared64)
OBJDIR = obj/shared64/Debug/dome
DEFINES += -DDOME_VERSION=\"$(VERSION)\" -DHASH=\"$(HASH)\" -DDEBUG=1
INCLUDES += -isystem src/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_LDFLAGS += $(LDFLAGS) -m64 -lwren `$(SDLCONFIG) --libs` -Lsrc/lib/

else ifeq ($(config),debug_static32)
OBJDIR = obj/static32/Debug/dome
DEFINES += -DDOME_VERSION=\"$(VERSION)\" -DHASH=\"$(HASH)\" -DDEBUG=1
INCLUDES += -isystem src/include -isystem src/include/SDL2
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -g -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_LDFLAGS += $(LDFLAGS) -L/Users/aviv.beeri/hobby/dome/src/lib -m32 -lwren  `$(SDLCONFIG) --static-libs` 

else ifeq ($(config),debug_shared32)
OBJDIR = obj/shared32/Debug/dome
DEFINES += -DDOME_VERSION=\"$(VERSION)\" -DHASH=\"$(HASH)\" -DDEBUG=1
INCLUDES += -isystem src/include
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -g -std=c99 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -g -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-unused-function -Wno-incompatible-pointer-types-discards-qualifiers -pedantic `$(SDLCONFIG) --cflags` -mmacosx-version-min=10.14
ALL_LDFLAGS += $(LDFLAGS) -m32 -lwren `$(SDLCONFIG) --libs` -Lsrc/lib/

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/main.o
OBJECTS += $(OBJDIR)/main.o

# Rules
# #############################################

all: $(TARGET) $(dir $(TARGETDIR))PkgInfo $(dir $(TARGETDIR))Info.plist
	@:

$(dir $(TARGETDIR))PkgInfo:
$(dir $(TARGETDIR))Info.plist:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking dome
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning dome
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(GENERATED)) rmdir /s /q $(subst /,\\,$(GENERATED))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/main.o: src/main.c
	@echo $(notdir $<)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif