# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release_static64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release_static64)
  DOME_config = release_static64

else ifeq ($(config),release_static32)
  DOME_config = release_static32

else ifeq ($(config),release_shared64)
  DOME_config = release_shared64

else ifeq ($(config),debug_static64)
  DOME_config = debug_static64

else ifeq ($(config),debug_static32)
  DOME_config = debug_static32

else ifeq ($(config),debug_shared64)
  DOME_config = debug_shared64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := DOME

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

DOME:
ifneq (,$(DOME_config))
	@echo "==== Building DOME ($(DOME_config)) ===="
	@${MAKE} --no-print-directory -C . -f DOME.make config=$(DOME_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f DOME.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release_static64"
	@echo "  release_static32"
	@echo "  release_shared64"
	@echo "  debug_static64"
	@echo "  debug_static32"
	@echo "  debug_shared64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   DOME"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"