# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release_shared64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release_static64)
  wren_config = release_static64
  modules_config = release_static64
  dome_config = release_static64

else ifeq ($(config),release_shared64)
  wren_config = release_shared64
  modules_config = release_shared64
  dome_config = release_shared64

else ifeq ($(config),release_static32)
  wren_config = release_static32
  modules_config = release_static32
  dome_config = release_static32

else ifeq ($(config),release_shared32)
  wren_config = release_shared32
  modules_config = release_shared32
  dome_config = release_shared32

else ifeq ($(config),debug_static64)
  wren_config = debug_static64
  modules_config = debug_static64
  dome_config = debug_static64

else ifeq ($(config),debug_shared64)
  wren_config = debug_shared64
  modules_config = debug_shared64
  dome_config = debug_shared64

else ifeq ($(config),debug_static32)
  wren_config = debug_static32
  modules_config = debug_static32
  dome_config = debug_static32

else ifeq ($(config),debug_shared32)
  wren_config = debug_shared32
  modules_config = debug_shared32
  dome_config = debug_shared32

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := wren modules dome

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

wren:
ifneq (,$(wren_config))
	@echo "==== Building wren ($(wren_config)) ===="
	@${MAKE} --no-print-directory -C . -f wren.make config=$(wren_config)
endif

modules:
ifneq (,$(modules_config))
	@echo "==== Building modules ($(modules_config)) ===="
	@${MAKE} --no-print-directory -C . -f modules.make config=$(modules_config)
endif

dome: wren modules
ifneq (,$(dome_config))
	@echo "==== Building dome ($(dome_config)) ===="
	@${MAKE} --no-print-directory -C . -f dome.make config=$(dome_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f wren.make clean
	@${MAKE} --no-print-directory -C . -f modules.make clean
	@${MAKE} --no-print-directory -C . -f dome.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release_static64"
	@echo "  release_shared64"
	@echo "  release_static32"
	@echo "  release_shared32"
	@echo "  debug_static64"
	@echo "  debug_shared64"
	@echo "  debug_static32"
	@echo "  debug_shared32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   wren"
	@echo "   modules"
	@echo "   dome"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"