# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=release_shared64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),release_static64)
TARGETDIR = src/lib
TARGET = $(TARGETDIR)/libwren.a
  define BUILDCMDS
	@echo Running build commands
	./scripts/setup_wren.sh 64bit WREN_OPT_RANDOM=1 WREN_OPT_META=1
  endef
  define CLEANCMDS
	@echo Running clean commands
	rm -f src/lib/libwren.a
	rm -f src/lib/libwrend.a
  endef

else ifeq ($(config),release_shared64)
TARGETDIR = src/lib
TARGET = $(TARGETDIR)/libwren.a
  define BUILDCMDS
	@echo Running build commands
	./scripts/setup_wren.sh 64bit WREN_OPT_RANDOM=1 WREN_OPT_META=1
  endef
  define CLEANCMDS
	@echo Running clean commands
	rm -f src/lib/libwren.a
	rm -f src/lib/libwrend.a
  endef

else ifeq ($(config),release_static32)
TARGETDIR = src/lib
TARGET = $(TARGETDIR)/libwren.a
  define BUILDCMDS
	@echo Running build commands
	./scripts/setup_wren.sh 32bit WREN_OPT_RANDOM=1 WREN_OPT_META=1
  endef
  define CLEANCMDS
	@echo Running clean commands
	rm -f src/lib/libwren.a
	rm -f src/lib/libwrend.a
  endef

else ifeq ($(config),release_shared32)
TARGETDIR = src/lib
TARGET = $(TARGETDIR)/libwren.a
  define BUILDCMDS
	@echo Running build commands
	./scripts/setup_wren.sh 32bit WREN_OPT_RANDOM=1 WREN_OPT_META=1
  endef
  define CLEANCMDS
	@echo Running clean commands
	rm -f src/lib/libwren.a
	rm -f src/lib/libwrend.a
  endef

else ifeq ($(config),debug_static64)
TARGETDIR = src/lib
TARGET = $(TARGETDIR)/libwrend.a
  define BUILDCMDS
	@echo Running build commands
	./scripts/setup_wren.sh 64bit WREN_OPT_RANDOM=1 WREN_OPT_META=1
  endef
  define CLEANCMDS
	@echo Running clean commands
	rm -f src/lib/libwren.a
	rm -f src/lib/libwrend.a
  endef

else ifeq ($(config),debug_shared64)
TARGETDIR = src/lib
TARGET = $(TARGETDIR)/libwrend.a
  define BUILDCMDS
	@echo Running build commands
	./scripts/setup_wren.sh 64bit WREN_OPT_RANDOM=1 WREN_OPT_META=1
  endef
  define CLEANCMDS
	@echo Running clean commands
	rm -f src/lib/libwren.a
	rm -f src/lib/libwrend.a
  endef

else ifeq ($(config),debug_static32)
TARGETDIR = src/lib
TARGET = $(TARGETDIR)/libwrend.a
  define BUILDCMDS
	@echo Running build commands
	./scripts/setup_wren.sh 32bit WREN_OPT_RANDOM=1 WREN_OPT_META=1
  endef
  define CLEANCMDS
	@echo Running clean commands
	rm -f src/lib/libwren.a
	rm -f src/lib/libwrend.a
  endef

else ifeq ($(config),debug_shared32)
TARGETDIR = src/lib
TARGET = $(TARGETDIR)/libwrend.a
  define BUILDCMDS
	@echo Running build commands
	./scripts/setup_wren.sh 32bit WREN_OPT_RANDOM=1 WREN_OPT_META=1
  endef
  define CLEANCMDS
	@echo Running clean commands
	rm -f src/lib/libwren.a
	rm -f src/lib/libwrend.a
  endef

else
  $(error "invalid configuration $(config)")
endif

DEPS=src/modules/*.wren
$(TARGET): $(DEPS)
	$(BUILDCMDS)

clean:
	$(CLEANCMDS)
